### PR TITLE
Bump @solid/oidc-rp to 0.10.0

### PR DESCRIPTION
**Pull request by CxRes**
Bumped @solid/oidc-rp to 0.10.0
@solid/oidc-rp 0.9.0 depends on @trust/webcrypto which is deprecated.

### CODE REVIEW

**Comment by CxRes** [comment]
Once this is bumped I would like to update solid-auth-cli as well!

**Review by jaxoncreed — APPROVED** [review]
LGTM :shipit:

**Comment by CxRes** [comment]
Fixes #11

**Comment by CxRes** [comment]
@jaxoncreed Do you want me to Bump the Patch Version as well or shall you do it?

**Comment by jaxoncreed** [comment]
I'll go ahead and do it and push to npm

**Pull request merged**
